sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-progress --no-interaction
  - ./vendor/bin/phpcs --config-set installed_paths $(pwd)
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --filter YaAPI --coverage-clover build/logs/clover.xml vendor/squizlabs/php_codesniffer/tests/AllTests.php
  - ./vendor/bin/phpcs -nsp --extensions=php --ignore=*/vendor/* --standard=YaAPI */

after_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then ./vendor/bin/coveralls -v; fi"

notifications:
  email: false