<?php
declare(encoding='utf-8');
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 *
 * Short description for file.
 *
 *
 * We also have a
 * long description for the file,
 * awesome.
 *
 * PHP version
 *
 * @category   _wrong_category
 * @package    YaAPI
 * @package      Additional Package Tag
 * @subpackage   Subpackage Tag
 * @author       Example Author author@example.org
 * @author     Mr T <t@example.org>
 * @author
 * @copyright  2015~2013 YaAPI
 * @copyright    YaAPI
 * @license    http://www.gnu.org/licenses/lgpl.txt
 * @license      http://www.gnu.org/licenses/lgpl.txt
 * @see
 * @version    INVALID VERSION CONTENT
 * @see        YaAPI::No_Function()
 * @see          YaAPI_Api
 * @deprecated abc
 * @since      Class available since Release 1.2.0
 * @summary    An unknown summary tag
 * @subpackage
 */
 ?>
 <?php
/**
 * Not qualified as a file comment.
 *
 * @copyright  Copyright (C) 2015 JoomWorker - http://joomworker.com - All rights reserved.
 * @license    GNU LESSER GENERAL PUBLIC LICENSE Version 2.1 or later - http://www.gnu.org
 */

$a = 'muh';
