<?php
class MyClass
{
    public function __yeahHaey()
    {
        return;
    }

    private function _coolPrivate()
    {
        return;
    }

    public function cool_name()
    {
        return;
    }

    public function coolName_Function()
    {
        return;
    }

    function cool_function()
    {
        return;
    }

    function _noPrivate()
    {
        return;
    }
}

class myClass
{
    public function myClass()
    {
        
    }

    public function _myClass()
    {
    
    }
}
