<?php
class MyClass
{
    public function __yeahHaey()
    {
        return;
    }

    private function _coolPrivate()
    {
        return;
    }

    public function cool_name()
    {
        return;
    }

    public function coolName_Function()
    {
        return;
    }

    function cool_function()
    {
        return;
    }

    function _noPrivate()
    {
        return;
    }
}

echo preg_replace_callback('~-([a-z])~', function ($match) { return strtoupper($match[1]); }, 'hello-world');

class myClass
{
    public function myClass()
    {
        
    }

    public function _myClass()
    {
    
    }
}
